server:
  port: 8880
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8880/eureka/

logging:
  config: classpath:logback.xml