server:
  port: 8881
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yb2020/spring-cloud-study-example.git
          username: your github username
          password: your github password
          search-paths: mirco-service-config



#  cloud:
#    config:
#      server:
#        svn:
#          uri: https://10.210.80.84/svn/YunNan/Project-Province/code/branches/dev_r1.0_exec/19年年初项目临时文件夹/config/test
#          username: qyh
#          password: qyh
#          default-label: file
#  profiles:
#    active: subversion

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
  instance:
    prefer-ip-address: true
    instance-id: config-server